// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CrimeRepository is an autogenerated mock type for the CrimeRepository type
type CrimeRepository struct {
	mock.Mock
}

type CrimeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CrimeRepository) EXPECT() *CrimeRepository_Expecter {
	return &CrimeRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, crime
func (_m *CrimeRepository) Create(ctx context.Context, crime *entities.Crime) error {
	ret := _m.Called(ctx, crime)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Crime) error); ok {
		r0 = rf(ctx, crime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CrimeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CrimeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - crime *entities.Crime
func (_e *CrimeRepository_Expecter) Create(ctx interface{}, crime interface{}) *CrimeRepository_Create_Call {
	return &CrimeRepository_Create_Call{Call: _e.mock.On("Create", ctx, crime)}
}

func (_c *CrimeRepository_Create_Call) Run(run func(ctx context.Context, crime *entities.Crime)) *CrimeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Crime))
	})
	return _c
}

func (_c *CrimeRepository_Create_Call) Return(_a0 error) *CrimeRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CrimeRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Crime) error) *CrimeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CrimeRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CrimeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CrimeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CrimeRepository_Expecter) Delete(ctx interface{}, id interface{}) *CrimeRepository_Delete_Call {
	return &CrimeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CrimeRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *CrimeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CrimeRepository_Delete_Call) Return(_a0 error) *CrimeRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CrimeRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *CrimeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CrimeRepository) GetByID(ctx context.Context, id int64) (*entities.Crime, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Crime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Crime, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Crime); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Crime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CrimeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CrimeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CrimeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CrimeRepository_GetByID_Call {
	return &CrimeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CrimeRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *CrimeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CrimeRepository_GetByID_Call) Return(_a0 *entities.Crime, _a1 error) *CrimeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CrimeRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*entities.Crime, error)) *CrimeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, uuid
func (_m *CrimeRepository) GetByUUID(ctx context.Context, uuid string) (*entities.Crime, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *entities.Crime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Crime, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Crime); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Crime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CrimeRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type CrimeRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *CrimeRepository_Expecter) GetByUUID(ctx interface{}, uuid interface{}) *CrimeRepository_GetByUUID_Call {
	return &CrimeRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid)}
}

func (_c *CrimeRepository_GetByUUID_Call) Run(run func(ctx context.Context, uuid string)) *CrimeRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CrimeRepository_GetByUUID_Call) Return(_a0 *entities.Crime, _a1 error) *CrimeRepository_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CrimeRepository_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (*entities.Crime, error)) *CrimeRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *CrimeRepository) GetStats(ctx context.Context) (*entities.CrimeStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *entities.CrimeStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.CrimeStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.CrimeStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CrimeStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CrimeRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type CrimeRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CrimeRepository_Expecter) GetStats(ctx interface{}) *CrimeRepository_GetStats_Call {
	return &CrimeRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *CrimeRepository_GetStats_Call) Run(run func(ctx context.Context)) *CrimeRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CrimeRepository_GetStats_Call) Return(_a0 *entities.CrimeStats, _a1 error) *CrimeRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CrimeRepository_GetStats_Call) RunAndReturn(run func(context.Context) (*entities.CrimeStats, error)) *CrimeRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit, startDate, endDate, crimeType, status
func (_m *CrimeRepository) List(ctx context.Context, page int, limit int, startDate *time.Time, endDate *time.Time, crimeType *string, status *string) ([]entities.Crime, int64, error) {
	ret := _m.Called(ctx, page, limit, startDate, endDate, crimeType, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entities.Crime
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *time.Time, *time.Time, *string, *string) ([]entities.Crime, int64, error)); ok {
		return rf(ctx, page, limit, startDate, endDate, crimeType, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *time.Time, *time.Time, *string, *string) []entities.Crime); ok {
		r0 = rf(ctx, page, limit, startDate, endDate, crimeType, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Crime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *time.Time, *time.Time, *string, *string) int64); ok {
		r1 = rf(ctx, page, limit, startDate, endDate, crimeType, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, *time.Time, *time.Time, *string, *string) error); ok {
		r2 = rf(ctx, page, limit, startDate, endDate, crimeType, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CrimeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CrimeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
//   - startDate *time.Time
//   - endDate *time.Time
//   - crimeType *string
//   - status *string
func (_e *CrimeRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}, startDate interface{}, endDate interface{}, crimeType interface{}, status interface{}) *CrimeRepository_List_Call {
	return &CrimeRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit, startDate, endDate, crimeType, status)}
}

func (_c *CrimeRepository_List_Call) Run(run func(ctx context.Context, page int, limit int, startDate *time.Time, endDate *time.Time, crimeType *string, status *string)) *CrimeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*time.Time), args[4].(*time.Time), args[5].(*string), args[6].(*string))
	})
	return _c
}

func (_c *CrimeRepository_List_Call) Return(_a0 []entities.Crime, _a1 int64, _a2 error) *CrimeRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *CrimeRepository_List_Call) RunAndReturn(run func(context.Context, int, int, *time.Time, *time.Time, *string, *string) ([]entities.Crime, int64, error)) *CrimeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, crime
func (_m *CrimeRepository) Update(ctx context.Context, crime *entities.Crime) error {
	ret := _m.Called(ctx, crime)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Crime) error); ok {
		r0 = rf(ctx, crime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CrimeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CrimeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - crime *entities.Crime
func (_e *CrimeRepository_Expecter) Update(ctx interface{}, crime interface{}) *CrimeRepository_Update_Call {
	return &CrimeRepository_Update_Call{Call: _e.mock.On("Update", ctx, crime)}
}

func (_c *CrimeRepository_Update_Call) Run(run func(ctx context.Context, crime *entities.Crime)) *CrimeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Crime))
	})
	return _c
}

func (_c *CrimeRepository_Update_Call) Return(_a0 error) *CrimeRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CrimeRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Crime) error) *CrimeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCrimeRepository creates a new instance of CrimeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCrimeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CrimeRepository {
	mock := &CrimeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
