// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// SecurityRepository is an autogenerated mock type for the SecurityRepository type
type SecurityRepository struct {
	mock.Mock
}

type SecurityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityRepository) EXPECT() *SecurityRepository_Expecter {
	return &SecurityRepository_Expecter{mock: &_m.Mock}
}

// ValidateAPIKey provides a mock function with given fields: ctx, apiKey
func (_m *SecurityRepository) ValidateAPIKey(ctx context.Context, apiKey string) (*entities.APIKey, error) {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAPIKey")
	}

	var r0 *entities.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.APIKey, error)); ok {
		return rf(ctx, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.APIKey); ok {
		r0 = rf(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecurityRepository_ValidateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAPIKey'
type SecurityRepository_ValidateAPIKey_Call struct {
	*mock.Call
}

// ValidateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *SecurityRepository_Expecter) ValidateAPIKey(ctx interface{}, apiKey interface{}) *SecurityRepository_ValidateAPIKey_Call {
	return &SecurityRepository_ValidateAPIKey_Call{Call: _e.mock.On("ValidateAPIKey", ctx, apiKey)}
}

func (_c *SecurityRepository_ValidateAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *SecurityRepository_ValidateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SecurityRepository_ValidateAPIKey_Call) Return(_a0 *entities.APIKey, _a1 error) *SecurityRepository_ValidateAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecurityRepository_ValidateAPIKey_Call) RunAndReturn(run func(context.Context, string) (*entities.APIKey, error)) *SecurityRepository_ValidateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewSecurityRepository creates a new instance of SecurityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityRepository {
	mock := &SecurityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
