// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeleteCrimeUseCaseInterface is an autogenerated mock type for the DeleteCrimeUseCaseInterface type
type MockDeleteCrimeUseCaseInterface struct {
	mock.Mock
}

type MockDeleteCrimeUseCaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteCrimeUseCaseInterface) EXPECT() *MockDeleteCrimeUseCaseInterface_Expecter {
	return &MockDeleteCrimeUseCaseInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id
func (_m *MockDeleteCrimeUseCaseInterface) Execute(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteCrimeUseCaseInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeleteCrimeUseCaseInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDeleteCrimeUseCaseInterface_Expecter) Execute(ctx interface{}, id interface{}) *MockDeleteCrimeUseCaseInterface_Execute_Call {
	return &MockDeleteCrimeUseCaseInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockDeleteCrimeUseCaseInterface_Execute_Call) Run(run func(ctx context.Context, id string)) *MockDeleteCrimeUseCaseInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeleteCrimeUseCaseInterface_Execute_Call) Return(_a0 error) *MockDeleteCrimeUseCaseInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteCrimeUseCaseInterface_Execute_Call) RunAndReturn(run func(context.Context, string) error) *MockDeleteCrimeUseCaseInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteCrimeUseCaseInterface creates a new instance of MockDeleteCrimeUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteCrimeUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteCrimeUseCaseInterface {
	mock := &MockDeleteCrimeUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
