// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetCrimeUseCaseInterface is an autogenerated mock type for the GetCrimeUseCaseInterface type
type MockGetCrimeUseCaseInterface struct {
	mock.Mock
}

type MockGetCrimeUseCaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCrimeUseCaseInterface) EXPECT() *MockGetCrimeUseCaseInterface_Expecter {
	return &MockGetCrimeUseCaseInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, id
func (_m *MockGetCrimeUseCaseInterface) Execute(ctx context.Context, id string) (*entities.Crime, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Crime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Crime, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Crime); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Crime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCrimeUseCaseInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetCrimeUseCaseInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGetCrimeUseCaseInterface_Expecter) Execute(ctx interface{}, id interface{}) *MockGetCrimeUseCaseInterface_Execute_Call {
	return &MockGetCrimeUseCaseInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockGetCrimeUseCaseInterface_Execute_Call) Run(run func(ctx context.Context, id string)) *MockGetCrimeUseCaseInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetCrimeUseCaseInterface_Execute_Call) Return(_a0 *entities.Crime, _a1 error) *MockGetCrimeUseCaseInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCrimeUseCaseInterface_Execute_Call) RunAndReturn(run func(context.Context, string) (*entities.Crime, error)) *MockGetCrimeUseCaseInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCrimeUseCaseInterface creates a new instance of MockGetCrimeUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCrimeUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCrimeUseCaseInterface {
	mock := &MockGetCrimeUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
