// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	usecases "go-crime_map_backend/internal/usecases"
)

// MockGetCrimeStatsUseCaseInterface is an autogenerated mock type for the GetCrimeStatsUseCaseInterface type
type MockGetCrimeStatsUseCaseInterface struct {
	mock.Mock
}

type MockGetCrimeStatsUseCaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCrimeStatsUseCaseInterface) EXPECT() *MockGetCrimeStatsUseCaseInterface_Expecter {
	return &MockGetCrimeStatsUseCaseInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockGetCrimeStatsUseCaseInterface) Execute(ctx context.Context, input usecases.GetCrimeStatsInput) (*entities.CrimeStats, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.CrimeStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.GetCrimeStatsInput) (*entities.CrimeStats, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.GetCrimeStatsInput) *entities.CrimeStats); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CrimeStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.GetCrimeStatsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCrimeStatsUseCaseInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetCrimeStatsUseCaseInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.GetCrimeStatsInput
func (_e *MockGetCrimeStatsUseCaseInterface_Expecter) Execute(ctx interface{}, input interface{}) *MockGetCrimeStatsUseCaseInterface_Execute_Call {
	return &MockGetCrimeStatsUseCaseInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetCrimeStatsUseCaseInterface_Execute_Call) Run(run func(ctx context.Context, input usecases.GetCrimeStatsInput)) *MockGetCrimeStatsUseCaseInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.GetCrimeStatsInput))
	})
	return _c
}

func (_c *MockGetCrimeStatsUseCaseInterface_Execute_Call) Return(_a0 *entities.CrimeStats, _a1 error) *MockGetCrimeStatsUseCaseInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCrimeStatsUseCaseInterface_Execute_Call) RunAndReturn(run func(context.Context, usecases.GetCrimeStatsInput) (*entities.CrimeStats, error)) *MockGetCrimeStatsUseCaseInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCrimeStatsUseCaseInterface creates a new instance of MockGetCrimeStatsUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCrimeStatsUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCrimeStatsUseCaseInterface {
	mock := &MockGetCrimeStatsUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
