// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	usecases "go-crime_map_backend/internal/usecases"

	mock "github.com/stretchr/testify/mock"
)

// MockListCrimesUseCaseInterface is an autogenerated mock type for the ListCrimesUseCaseInterface type
type MockListCrimesUseCaseInterface struct {
	mock.Mock
}

type MockListCrimesUseCaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListCrimesUseCaseInterface) EXPECT() *MockListCrimesUseCaseInterface_Expecter {
	return &MockListCrimesUseCaseInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockListCrimesUseCaseInterface) Execute(ctx context.Context, input usecases.ListCrimesInput) (*usecases.ListCrimesOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecases.ListCrimesOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.ListCrimesInput) (*usecases.ListCrimesOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.ListCrimesInput) *usecases.ListCrimesOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecases.ListCrimesOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.ListCrimesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListCrimesUseCaseInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockListCrimesUseCaseInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.ListCrimesInput
func (_e *MockListCrimesUseCaseInterface_Expecter) Execute(ctx interface{}, input interface{}) *MockListCrimesUseCaseInterface_Execute_Call {
	return &MockListCrimesUseCaseInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockListCrimesUseCaseInterface_Execute_Call) Run(run func(ctx context.Context, input usecases.ListCrimesInput)) *MockListCrimesUseCaseInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.ListCrimesInput))
	})
	return _c
}

func (_c *MockListCrimesUseCaseInterface_Execute_Call) Return(_a0 *usecases.ListCrimesOutput, _a1 error) *MockListCrimesUseCaseInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListCrimesUseCaseInterface_Execute_Call) RunAndReturn(run func(context.Context, usecases.ListCrimesInput) (*usecases.ListCrimesOutput, error)) *MockListCrimesUseCaseInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListCrimesUseCaseInterface creates a new instance of MockListCrimesUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListCrimesUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListCrimesUseCaseInterface {
	mock := &MockListCrimesUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
