// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	usecases "go-crime_map_backend/internal/usecases"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateCrimeStatusUseCaseInterface is an autogenerated mock type for the UpdateCrimeStatusUseCaseInterface type
type MockUpdateCrimeStatusUseCaseInterface struct {
	mock.Mock
}

type MockUpdateCrimeStatusUseCaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateCrimeStatusUseCaseInterface) EXPECT() *MockUpdateCrimeStatusUseCaseInterface_Expecter {
	return &MockUpdateCrimeStatusUseCaseInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockUpdateCrimeStatusUseCaseInterface) Execute(ctx context.Context, input usecases.UpdateCrimeStatusInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.UpdateCrimeStatusInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateCrimeStatusUseCaseInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateCrimeStatusUseCaseInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.UpdateCrimeStatusInput
func (_e *MockUpdateCrimeStatusUseCaseInterface_Expecter) Execute(ctx interface{}, input interface{}) *MockUpdateCrimeStatusUseCaseInterface_Execute_Call {
	return &MockUpdateCrimeStatusUseCaseInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockUpdateCrimeStatusUseCaseInterface_Execute_Call) Run(run func(ctx context.Context, input usecases.UpdateCrimeStatusInput)) *MockUpdateCrimeStatusUseCaseInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.UpdateCrimeStatusInput))
	})
	return _c
}

func (_c *MockUpdateCrimeStatusUseCaseInterface_Execute_Call) Return(_a0 error) *MockUpdateCrimeStatusUseCaseInterface_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateCrimeStatusUseCaseInterface_Execute_Call) RunAndReturn(run func(context.Context, usecases.UpdateCrimeStatusInput) error) *MockUpdateCrimeStatusUseCaseInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateCrimeStatusUseCaseInterface creates a new instance of MockUpdateCrimeStatusUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateCrimeStatusUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateCrimeStatusUseCaseInterface {
	mock := &MockUpdateCrimeStatusUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
