// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	usecases "go-crime_map_backend/internal/domain/usecases"
)

// CreateCrimeUseCase is an autogenerated mock type for the CreateCrimeUseCase type
type CreateCrimeUseCase struct {
	mock.Mock
}

type CreateCrimeUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateCrimeUseCase) EXPECT() *CreateCrimeUseCase_Expecter {
	return &CreateCrimeUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *CreateCrimeUseCase) Execute(ctx context.Context, input usecases.CreateCrimeInput) (*entities.Crime, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Crime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.CreateCrimeInput) (*entities.Crime, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.CreateCrimeInput) *entities.Crime); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Crime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.CreateCrimeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCrimeUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateCrimeUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.CreateCrimeInput
func (_e *CreateCrimeUseCase_Expecter) Execute(ctx interface{}, input interface{}) *CreateCrimeUseCase_Execute_Call {
	return &CreateCrimeUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *CreateCrimeUseCase_Execute_Call) Run(run func(ctx context.Context, input usecases.CreateCrimeInput)) *CreateCrimeUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.CreateCrimeInput))
	})
	return _c
}

func (_c *CreateCrimeUseCase_Execute_Call) Return(_a0 *entities.Crime, _a1 error) *CreateCrimeUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreateCrimeUseCase_Execute_Call) RunAndReturn(run func(context.Context, usecases.CreateCrimeInput) (*entities.Crime, error)) *CreateCrimeUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateCrimeUseCase creates a new instance of CreateCrimeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCrimeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCrimeUseCase {
	mock := &CreateCrimeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
