// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteCrimeUseCase is an autogenerated mock type for the DeleteCrimeUseCase type
type DeleteCrimeUseCase struct {
	mock.Mock
}

type DeleteCrimeUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteCrimeUseCase) EXPECT() *DeleteCrimeUseCase_Expecter {
	return &DeleteCrimeUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, uuid
func (_m *DeleteCrimeUseCase) Execute(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCrimeUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteCrimeUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *DeleteCrimeUseCase_Expecter) Execute(ctx interface{}, uuid interface{}) *DeleteCrimeUseCase_Execute_Call {
	return &DeleteCrimeUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, uuid)}
}

func (_c *DeleteCrimeUseCase_Execute_Call) Run(run func(ctx context.Context, uuid string)) *DeleteCrimeUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeleteCrimeUseCase_Execute_Call) Return(_a0 error) *DeleteCrimeUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteCrimeUseCase_Execute_Call) RunAndReturn(run func(context.Context, string) error) *DeleteCrimeUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteCrimeUseCase creates a new instance of DeleteCrimeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteCrimeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteCrimeUseCase {
	mock := &DeleteCrimeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
