// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// GetCrimeUseCase is an autogenerated mock type for the GetCrimeUseCase type
type GetCrimeUseCase struct {
	mock.Mock
}

type GetCrimeUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetCrimeUseCase) EXPECT() *GetCrimeUseCase_Expecter {
	return &GetCrimeUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, uuid
func (_m *GetCrimeUseCase) Execute(ctx context.Context, uuid string) (*entities.Crime, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Crime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Crime, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Crime); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Crime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCrimeUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetCrimeUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *GetCrimeUseCase_Expecter) Execute(ctx interface{}, uuid interface{}) *GetCrimeUseCase_Execute_Call {
	return &GetCrimeUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, uuid)}
}

func (_c *GetCrimeUseCase_Execute_Call) Run(run func(ctx context.Context, uuid string)) *GetCrimeUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GetCrimeUseCase_Execute_Call) Return(_a0 *entities.Crime, _a1 error) *GetCrimeUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetCrimeUseCase_Execute_Call) RunAndReturn(run func(context.Context, string) (*entities.Crime, error)) *GetCrimeUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetCrimeUseCase creates a new instance of GetCrimeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetCrimeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetCrimeUseCase {
	mock := &GetCrimeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
