// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// GetCrimeStatsUseCase is an autogenerated mock type for the GetCrimeStatsUseCase type
type GetCrimeStatsUseCase struct {
	mock.Mock
}

type GetCrimeStatsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetCrimeStatsUseCase) EXPECT() *GetCrimeStatsUseCase_Expecter {
	return &GetCrimeStatsUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *GetCrimeStatsUseCase) Execute(ctx context.Context) (*entities.CrimeStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.CrimeStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.CrimeStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.CrimeStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CrimeStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCrimeStatsUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetCrimeStatsUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GetCrimeStatsUseCase_Expecter) Execute(ctx interface{}) *GetCrimeStatsUseCase_Execute_Call {
	return &GetCrimeStatsUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *GetCrimeStatsUseCase_Execute_Call) Run(run func(ctx context.Context)) *GetCrimeStatsUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GetCrimeStatsUseCase_Execute_Call) Return(_a0 *entities.CrimeStats, _a1 error) *GetCrimeStatsUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetCrimeStatsUseCase_Execute_Call) RunAndReturn(run func(context.Context) (*entities.CrimeStats, error)) *GetCrimeStatsUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetCrimeStatsUseCase creates a new instance of GetCrimeStatsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetCrimeStatsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetCrimeStatsUseCase {
	mock := &GetCrimeStatsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
