// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "go-crime_map_backend/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	usecases "go-crime_map_backend/internal/domain/usecases"
)

// ListCrimesUseCase is an autogenerated mock type for the ListCrimesUseCase type
type ListCrimesUseCase struct {
	mock.Mock
}

type ListCrimesUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *ListCrimesUseCase) EXPECT() *ListCrimesUseCase_Expecter {
	return &ListCrimesUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, params
func (_m *ListCrimesUseCase) Execute(ctx context.Context, params usecases.ListCrimesParams) (*entities.CrimeList, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.CrimeList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.ListCrimesParams) (*entities.CrimeList, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.ListCrimesParams) *entities.CrimeList); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CrimeList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.ListCrimesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCrimesUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListCrimesUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - params usecases.ListCrimesParams
func (_e *ListCrimesUseCase_Expecter) Execute(ctx interface{}, params interface{}) *ListCrimesUseCase_Execute_Call {
	return &ListCrimesUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, params)}
}

func (_c *ListCrimesUseCase_Execute_Call) Run(run func(ctx context.Context, params usecases.ListCrimesParams)) *ListCrimesUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.ListCrimesParams))
	})
	return _c
}

func (_c *ListCrimesUseCase_Execute_Call) Return(_a0 *entities.CrimeList, _a1 error) *ListCrimesUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListCrimesUseCase_Execute_Call) RunAndReturn(run func(context.Context, usecases.ListCrimesParams) (*entities.CrimeList, error)) *ListCrimesUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListCrimesUseCase creates a new instance of ListCrimesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListCrimesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListCrimesUseCase {
	mock := &ListCrimesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
