// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	usecases "go-crime_map_backend/internal/domain/usecases"

	mock "github.com/stretchr/testify/mock"
)

// UpdateCrimeStatusUseCase is an autogenerated mock type for the UpdateCrimeStatusUseCase type
type UpdateCrimeStatusUseCase struct {
	mock.Mock
}

type UpdateCrimeStatusUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateCrimeStatusUseCase) EXPECT() *UpdateCrimeStatusUseCase_Expecter {
	return &UpdateCrimeStatusUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *UpdateCrimeStatusUseCase) Execute(ctx context.Context, input usecases.UpdateCrimeStatusInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.UpdateCrimeStatusInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCrimeStatusUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateCrimeStatusUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.UpdateCrimeStatusInput
func (_e *UpdateCrimeStatusUseCase_Expecter) Execute(ctx interface{}, input interface{}) *UpdateCrimeStatusUseCase_Execute_Call {
	return &UpdateCrimeStatusUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *UpdateCrimeStatusUseCase_Execute_Call) Run(run func(ctx context.Context, input usecases.UpdateCrimeStatusInput)) *UpdateCrimeStatusUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.UpdateCrimeStatusInput))
	})
	return _c
}

func (_c *UpdateCrimeStatusUseCase_Execute_Call) Return(_a0 error) *UpdateCrimeStatusUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UpdateCrimeStatusUseCase_Execute_Call) RunAndReturn(run func(context.Context, usecases.UpdateCrimeStatusInput) error) *UpdateCrimeStatusUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdateCrimeStatusUseCase creates a new instance of UpdateCrimeStatusUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateCrimeStatusUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateCrimeStatusUseCase {
	mock := &UpdateCrimeStatusUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
